name: Conditions

on:
  workflow_dispatch:

jobs:
  conditions:
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.run_id }}
    steps:
      - run: echo "Hello $RUN_ID"
        # ワークフローIDの最後が1である場合のみ実行
        if: endsWith(env.RUN_ID, '1')
