name: Manual

on:
  workflow_dispatch: # 手動実行イベント
    inputs:
      greeting: # 入力パラメータ例
        type: string # データ型（文字列）
        default: Hello # 入力パラメータのデフォルト値
        required: false # 入力パラメータの必須フラグ
        description: A cheerful word # 入力パラメータの概要

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ inputs.greeting }}, world!"
