name: Contexts

on: push

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Github context is ${{ toJson(github) }}"

      - run: echo "Runner context is ${{ toJson(runner) }}"
