name: Conditions

on:
  workflow_dispatch:

jobs:
  conditions:
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.run_id }}
    steps:
      - run: echo "Hello $RUN_ID"
        if: ${{contains(github.run_id , '1')}} # ワークフローIDが1である場合のみ実行
