name: Log group

on:
  push:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log group
        run: |
          echo "::group::Show environment variables" # ロググループ化の開始
          printenv
          echo "::endgroup::" # ロググループ化の終了
