name: Parallel jobs

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "This is the first job"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "This is the second job"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "This is the third job"
