name: Variables and secrets

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }} # 変数を環境変数に設定
      PASSWORD: ${{ secrets.PASSWORD }} # シークレットを環境変数に設定
    
    steps:
      - run: echo "The username is ${USERNAME}" # 環境変数経由で変数を参照
      - run: echo "The password is ${PASSWORD}" # 環境変数経由でシークレットを参照
